-- Gold layer: analytics-ready feature tables.
-- Parameterize {{catalog}}. These CREATE OR REPLACE statements mirror the SQL
-- generated by fred_pipeline.gold; ship them for engineers who prefer to build
-- Gold from pure SQL / a SQL Warehouse instead of the Python job.

USE CATALOG {{catalog}};

-- Full vintage history (point-in-time / ALFRED-style).
CREATE OR REPLACE TABLE gold.fred_point_in_time AS
SELECT
    series_id,
    observation_date,
    realtime_start,
    realtime_end,
    value,
    revision_number,
    is_missing,
    ingested_at
FROM silver.fred_observation;

-- One row per (series, date) at its latest revision ("as revised today").
CREATE OR REPLACE TABLE gold.fred_latest_observation AS
WITH ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY series_id, observation_date
            ORDER BY realtime_start DESC
        ) AS rn
    FROM silver.fred_observation
)
SELECT
    series_id,
    observation_date,
    value,
    realtime_start,
    realtime_end,
    is_missing,
    revision_number,
    ingested_at
FROM ranked
WHERE rn = 1;

-- Daily, forward-filled feature matrix for optimizer / ML inputs.
CREATE OR REPLACE TABLE gold.fred_macro_feature_daily AS
WITH bounds AS (
    SELECT MIN(observation_date) AS min_d, MAX(observation_date) AS max_d
    FROM gold.fred_latest_observation
),
calendar AS (
    SELECT explode(sequence(
        (SELECT min_d FROM bounds),
        (SELECT max_d FROM bounds),
        INTERVAL 1 DAY
    )) AS as_of_date
),
series_list AS (
    SELECT DISTINCT series_id FROM gold.fred_latest_observation
),
grid AS (
    SELECT c.as_of_date, s.series_id
    FROM calendar c CROSS JOIN series_list s
),
joined AS (
    SELECT
        g.as_of_date,
        g.series_id,
        l.value,
        last_value(l.value, true) OVER (
            PARTITION BY g.series_id ORDER BY g.as_of_date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS value_ffill
    FROM grid g
    LEFT JOIN gold.fred_latest_observation l
      ON g.series_id = l.series_id AND g.as_of_date = l.observation_date
)
SELECT as_of_date, series_id, value AS raw_value, value_ffill AS value
FROM joined;
