-- Gold layer: analytics-ready feature tables.
-- Parameterize {{catalog}}. These CREATE OR REPLACE statements mirror the SQL
-- generated by fred_pipeline.gold; ship them for engineers who prefer to build
-- Gold from pure SQL / a SQL Warehouse instead of the Python job.

USE CATALOG {{catalog}};

-- Full vintage history (point-in-time / ALFRED-style).
CREATE OR REPLACE TABLE gold.fred_point_in_time AS
SELECT
    series_id,
    observation_date,
    realtime_start,
    realtime_end,
    value,
    revision_number,
    is_missing,
    ingested_at
FROM silver.fred_observation;

-- One row per (series, date) at its latest revision ("as revised today").
CREATE OR REPLACE TABLE gold.fred_latest_observation AS
WITH ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY series_id, observation_date
            ORDER BY realtime_start DESC
        ) AS rn
    FROM silver.fred_observation
)
SELECT
    series_id,
    observation_date,
    value,
    realtime_start,
    realtime_end,
    is_missing,
    revision_number,
    ingested_at
FROM ranked
WHERE rn = 1;

-- Daily, forward-filled feature matrix for optimizer / ML inputs.
CREATE OR REPLACE TABLE gold.fred_macro_feature_daily AS
WITH bounds AS (
    SELECT MIN(observation_date) AS min_d, MAX(observation_date) AS max_d
    FROM gold.fred_latest_observation
),
calendar AS (
    SELECT explode(sequence(
        (SELECT min_d FROM bounds),
        (SELECT max_d FROM bounds),
        INTERVAL 1 DAY
    )) AS as_of_date
),
series_list AS (
    SELECT DISTINCT series_id FROM gold.fred_latest_observation
),
grid AS (
    SELECT c.as_of_date, s.series_id
    FROM calendar c CROSS JOIN series_list s
),
joined AS (
    SELECT
        g.as_of_date,
        g.series_id,
        l.value,
        last_value(l.value, true) OVER (
            PARTITION BY g.series_id ORDER BY g.as_of_date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS value_ffill
    FROM grid g
    LEFT JOIN gold.fred_latest_observation l
      ON g.series_id = l.series_id AND g.as_of_date = l.observation_date
)
SELECT as_of_date, series_id, value AS raw_value, value_ffill AS value
FROM joined;

-- Quant transforms: MoM / first diff / YoY / expanding (point-in-time safe)
-- z-score per series. The mean_v/std_v window frame is bounded to
-- UNBOUNDED PRECEDING..CURRENT ROW so each row only reflects observations
-- at-or-before its own date -- a whole-partition aggregate would leak future
-- values into every historical row.
CREATE OR REPLACE TABLE gold.fred_feature_transforms AS
WITH base AS (
    SELECT series_id, observation_date, value
    FROM gold.fred_latest_observation WHERE is_missing = false
),
w AS (
    SELECT series_id, observation_date, value,
        LAG(value) OVER (PARTITION BY series_id ORDER BY observation_date) AS prev_value,
        AVG(value) OVER (
            PARTITION BY series_id ORDER BY observation_date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS mean_v,
        STDDEV_POP(value) OVER (
            PARTITION BY series_id ORDER BY observation_date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS std_v
    FROM base
),
ya AS (
    SELECT a.*, b.value AS year_ago
    FROM w a
    LEFT JOIN base b
      ON b.series_id = a.series_id
     AND b.observation_date = add_months(a.observation_date, -12)
)
SELECT series_id, observation_date, value,
    CASE WHEN prev_value IS NOT NULL AND prev_value <> 0
         THEN (value - prev_value) / prev_value END AS mom,
    CASE WHEN prev_value IS NOT NULL THEN value - prev_value END AS diff,
    CASE WHEN year_ago IS NOT NULL AND year_ago <> 0
         THEN (value - year_ago) / year_ago END AS yoy,
    CASE WHEN std_v IS NOT NULL AND std_v <> 0
         THEN (value - mean_v) / std_v END AS zscore
FROM ya;

-- Yield-curve spreads (long_leg − short_leg) over the seed universe.
CREATE OR REPLACE TABLE gold.fred_curve_spread AS
SELECT s.spread_name, a.observation_date, s.long_leg, s.short_leg,
       a.value - b.value AS value
FROM (VALUES
        ('T10Y2Y',  'DGS10', 'DGS2'),
        ('T10Y3M',  'DGS10', 'DGS3MO'),
        ('T2Y3M',   'DGS2',  'DGS3MO'),
        ('T30Y10Y', 'DGS30', 'DGS10')
     ) AS s(spread_name, long_leg, short_leg)
JOIN gold.fred_latest_observation a ON a.series_id = s.long_leg  AND a.is_missing = false
JOIN gold.fred_latest_observation b ON b.series_id = s.short_leg AND b.is_missing = false
                                   AND b.observation_date = a.observation_date;

-- Revision magnitude: how much each observation moved between its first
-- print and today. Reads raw Silver (every vintage), not gold.fred_latest_
-- observation, since it exists to measure revision behavior itself.
-- Non-vintage series (blank realtime_start) always have revision_count = 1.
CREATE OR REPLACE TABLE gold.fred_revision_stats AS
WITH base AS (
    SELECT series_id, observation_date, realtime_start, value, revision_number
    FROM silver.fred_observation
    WHERE is_missing = false AND value IS NOT NULL
),
bounds AS (
    SELECT series_id, observation_date,
        MIN(revision_number) AS min_rev, MAX(revision_number) AS max_rev,
        COUNT(*) AS revision_count
    FROM base
    GROUP BY series_id, observation_date
)
SELECT b.series_id, b.observation_date, b.revision_count,
    f.value AS first_value, f.realtime_start AS first_realtime_start,
    l.value AS latest_value, l.realtime_start AS latest_realtime_start,
    l.value - f.value AS revision_delta,
    CASE WHEN f.value <> 0 THEN (l.value - f.value) / f.value END AS revision_pct
FROM bounds b
JOIN base f ON f.series_id = b.series_id AND f.observation_date = b.observation_date
          AND f.revision_number = b.min_rev
JOIN base l ON l.series_id = b.series_id AND l.observation_date = b.observation_date
          AND l.revision_number = b.max_rev;
